### ISSUE TITLE
@auto scope

### ISSUE THREAD

**Issue by hipstersmoothie** [bubble-dev/_#14]
Hey! looks like we made quite the similar thing 😄 

https://github.com/intuit/auto

We recently moved to a monorepo and would really like if we could get the @auto scope. It's no big deal if you don't want to, I understand. But since our names kinda step on each other and could lead to user confusion it might be good to differentiate the tech.

How do you feel about this?

Thanks for your time!

**Comment by deepsweet** [comment]
Hi.

The original project was started [here](https://github.com/deepsweet/auto), so our `@auto` is actually 9 months old. Sorry but we don't have plans to drop the project or the NPM scope with many packages.
