### ISSUE TITLE
Error when installing @start/cli

### ISSUE THREAD

**Issue by qw6200** [bubble-dev/_#236]
When attempting to install v1.0.0 of @start/cli, there is a chmod error.
It seems to be working fine in earlier versions like v0.0.5.
<img width="951" alt="Screen Shot 2020-02-03 at 4 49 56 PM" src="https://user-images.githubusercontent.com/25855866/73694088-64a05a00-46a5-11ea-939b-47b7ebf0a29d.png">

**Comment by deepsweet** [comment]
should be fixed in `@start/cli@1.0.1`, thanks for reporting.
